version: '3.8'

services:
  snake-front:
    build:
      context: ./ 
      dockerfile: front-end/vue-project/dockerfile
    container_name: snake-front
    ports:
      - "8080:8080"
    networks:
      - app_network

  snake-back:
    build:
      context: ./ 
      dockerfile: back-end/Dockerfile
    container_name: snake-back
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - ./back-end/db.sqlite3:/app/db.sqlite3  

networks:
  app_network:
    driver: bridge
